package com.uitstalie.neotrition.api.data.item;

import net.minecraft.resources.ResourceLocation;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * BFS 自动推断的营养组归属缓存（低优先级，manual JSON + data pack tag 优先）。
 *
 * <p>0.0.3 重构：不再存储 per_value，改为存储 item → groups 映射。
 * 消费时与 item tag 查询合并。</p>
 */
public class AutoGeneratedItemNutritionSource implements ItemNutritionSource {

    private final Map<ResourceLocation, NutritionItemJson> items = new LinkedHashMap<>();
    private final Map<ResourceLocation, Set<String>> groups = new HashMap<>();

    @Override
    public List<NutritionItemJson> getItems() {
        return items.values().stream().toList();
    }

    /**
     * 获取 BFS 推断的 group 归属。
     *
     * @return item 所属的 group 集合，未推断则返回空集
     */
    @Override
    public Set<String> getGroupsForItem(String itemId) {
        if (itemId == null) return Set.of();
        Set<String> result = groups.get(ResourceLocation.parse(itemId));
        return result != null ? result : Set.of();
    }

    /**
     * 获取 BFS 推断的 group 归属（ResourceLocation 版本）。
     *
     * @return item 所属的 group 集合，未推断则返回 null
     */
    public Set<String> getGroups(ResourceLocation itemId) {
        return itemId == null ? null : groups.get(itemId);
    }

    public void clear() {
        items.clear();
        groups.clear();
    }

    /** 获取所有 BFS 推断的 item → groups 映射（只读）。 */
    public Map<ResourceLocation, Set<String>> getAllGroups() {
        return java.util.Collections.unmodifiableMap(groups);
    }

    public void put(ResourceLocation itemId, NutritionItemJson itemJson) {
        if (itemId != null && itemJson != null) {
            items.put(itemId, itemJson);
        }
    }

    public void putGroups(ResourceLocation itemId, Set<String> itemGroups) {
        if (itemId != null && itemGroups != null && !itemGroups.isEmpty()) {
            groups.put(itemId, itemGroups);
        }
    }

    /**
     * 将 BFS 推断结果（item → groups）转换为 {@link NutritionItemJson} 列表，
     * 使 {@link #getItems()} 能正确返回自动生成的数据。
     * <p>在 BFS + FeastBlock 传播完成后调用一次即可。</p>
     */
    public void buildItems() {
        items.clear();
        // 反转映射：groupName → [item entries]
        Map<String, List<NutritionItemJson.ItemEntry>> groupToItems = new LinkedHashMap<>();
        for (var entry : groups.entrySet()) {
            String itemId = entry.getKey().toString();
            for (String groupName : entry.getValue()) {
                groupToItems.computeIfAbsent(groupName, k -> new ArrayList<>())
                        .add(new NutritionItemJson.ItemEntry(itemId, null));
            }
        }
        for (var entry : groupToItems.entrySet()) {
            items.put(ResourceLocation.parse("autogen:" + entry.getKey()),
                    new NutritionItemJson(entry.getKey(), entry.getValue()));
        }
    }
}
